apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-loan-services-deployment
  labels:
    app: demo-loan-services-kuberapp
spec:
  selector:
    matchLabels:
      app: demo-loan-services-kuberapp
  template:
    metadata:
      labels:
        app: demo-loan-services-kuberapp
    spec:
      containers:
      - name: demo-loan-services
        image: gshenbagavel/demo-loan-services:latest
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: demo-loan-services-kuberapp
spec:
  selector:
    app: demo-loan-services-kuberapp
  ports:
    - port: 9100
      targetPort: 9100
      nodePort: 30008
  type: LoadBalancer
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: demo-loan-services-kuberapp-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app:  demo-loan-services-kuberapp